### ISSUE TITLE
Configurable preview size

### ISSUE THREAD

**Issue by mikeclayton** [mikeclayton/FancyMouse#14]
FancyMouse reads the preview image size from a config file, but it doesn’t have any settings UI to edit it, other than in a text editor.

Add a settings dialog…

(Also have a look at adding it as a setting in PowerToys Mouse Jump - see https://github.com/microsoft/PowerToys/issues/24564)

**Comment by mikeclayton** [comment]
Note - preview size (and shortcut keys) *can* currently be configured in FancyMouse.json, but there's no UI for it:

**FancyMouse.json**
```json
{
  "FancyMouse": {
    "Hotkey": "CTRL + ALT + SHIFT + F",
    "Preview": "1600 x 1200"
  }
}
```

**Comment by mdrejhon** [comment]
Thanks!   

As Blur Busters / TestUFO founder, when I'm connecting too many monitors -- I actually prefer a really tiny preview (e.g. 200x200 pixels) for a massively multimonitor system -- just to click the correct monitor.   

I use the Razer 8KHz mouse + no acceleration + 1600dpi operation, and it's a pretty fast accurate glide even over 2000-4000 pixels in one swipe -- and I can still single-pixel click in bitmap editors.   So I only need to aim coarsely on one monitor, if I have too many monitors connected to easily track the mouse cursor.  

This utility is like "Find My Mouse" (because the tiny preview popup is like a spotlight that appears near the cursor) -- so I only need to click on the monitor I want to teleport the mouse pointer to.

**Comment by mdrejhon** [comment]
I just updated my PowerToys and ... I see this change is in the PowerToys side!

I've made comment of apprecation at https://github.com/microsoft/PowerToys/issues/24564#issuecomment-1554100916

## Niche Use Case

Since I am a display testing laboratory (Blur Busters / TestUFO), I sometimes randomly hotplug displays, and I just want to teleport to the correct monitor, so I hated the ginormously oversized preview.  This setting fixes that!  Especially if the monitor is behind me on a long fiber-optic HDMI cable, or the monitor sitting on a different table at a 90-degree angle. You can't layout such weird setups in Control Panel, but Mouse Jump makes it easy!

## Mainstream Use Case

Or the more mainstream use case -- of putting a laptop on the floor/coffeetable -- or weird-angle next to a television set forced by a short HDMI cable (and it weirds-up the multimonitor layout) -- where lots do today to play content from laptop to TV -- and sometimes has no resemblance to the multimonitor layout in Windows Control Panel. And back from college/university the next day, the laptop is now on the opposite side of TV instead, making the multimonitor layout settings outdated.

**Comment by mikeclayton** [comment]
@mdrejhon - Thanks for the feedback - it's always nice to hear it's useful for other people too :-).

Using it as a "screen jump" like you've described makes sense if you've got lots of hardware churn. I guess it doesn't solve dragging applications between screens, but that's what PowerToys FancyZones is for I guess...

I kind of use FancyMouse / Mouse Jumpit half-way between a pixel-perfect jump util and a coarse-grained monitor-level selector - I tend to click *roughtly* where I want it and fine tune it once it's moved - that seems to be a good compromise between spending extra seconds clicking the *exact* pixel on the thumbnail while still landing *close* to where you want it to be.

Out of interest, do you activate it with the keyboard combination, or have you bound it to a mouse button like this - https://github.com/microsoft/PowerToys/issues/24512#issuecomment-1453324221 ?

And if you want to add separate tickets for "configurable monitor borders" and "background dimming" I'll add some comments to those...

**Comment by mdrejhon** [comment]
Hotkey for now, though I'm still figuring out what workflow to use, now that this utility has become more useful when I've got excess monitors.  

The more monitors connected, the more I use it.  I may have periods of stability -- I often stay on my Corsair Xeneon Flex 240Hz OLED prototype (I help display manufacturers) as it is a nice big monitor for everything-usage.

I'll add separate items for those.

**Comment by mikeclayton** [comment]
Closing this ticket in favour of the more general #32 - Settings UI
