### ISSUE TITLE
Configurable display borders

### ISSUE THREAD

**Issue by mdrejhon** [mikeclayton/FancyMouse#19]
Hello,

I'd love to see the following configurability:

* Configurable display border color (priority for me)
* Configurable display border thickness (nice-to-have)
* Whether you want only one boundary around all multimonitor, or each individual monitor

Preferably, I'd love to see it have boundaries around each monitor, maybe even with a tiny amount of spacing between them (so they're a series of unique rectangles).  But I'll go with what UX compromises you make to simplify the number of settings -- just want good visibility.  I want to use a blatant color, like yellow or near-whites.

Inspired from #14

**Comment by mikeclayton** [comment]
I thought about doing this a while ago with "realistic" screen bezels - something like this:

![bezels-grey](https://github.com/mikeclayton/FancyMouse/assets/1193763/7f399129-7591-40ed-b6f8-73a35c77d9fe)

which could  have had colour (and thickness) settings added to make high-contrast variations like this:

![bezels-orange](https://github.com/mikeclayton/FancyMouse/assets/1193763/939047e2-895d-4b75-89bd-ad10e3377eec)

*but* it started falling apart a bit when I tried to work through some more complicated scenarios - e.g. this screen layout:

![layout-no-bezel](https://github.com/mikeclayton/FancyMouse/assets/1193763/ab420c00-331c-46cb-af78-6286b76e5bac)

Working out how to space out the monitors to make room for the bezels around each screenshot melted my brain a bit, and even if you did it, the result didn't look very pretty because the alignment was all messed up:

![layout-with-bezel](https://github.com/mikeclayton/FancyMouse/assets/1193763/17e75ef8-668d-45aa-8606-dd180b54809f)

So I thought maybe you could draw the bezels *inside* the existing screen areas which solved the distorted alignment:

![layout-inner-bezel](https://github.com/mikeclayton/FancyMouse/assets/1193763/9e1263f5-fe85-4f34-885c-721e22dc20e1)

but that reduces the size of each screen thumbnail image by 2 x the thickness of the bezel in each direction, which alters the aspect ratio of each screenshot- e.g. a 200 x 150 thumbnail of a 4:3 screen would now be a 180 x 130 thumbnail inside a 10-pixel thick surrounding bezel, making the aspect ratio roughly 4:2.89 instead, and you'd have to distort the screenshot slightly to fit it inside the bezel.

I don't know if that would really matter visually in the scheme of things, tbh, *but* it also complicated mapping the mouse click back to a desktop location because now you've got invalid click areas (e.g. the bezel) and you can't just scale the click location relative to the popup form - you need to track a number of different hit-boxes and map those back individually, bearing in mind each screen's thumbnail might have wonky (and different) aspect ratios.

Ultimately it's all just basic maths and it's *doable*, but I wasn't quite ready to try to bite off this piece of work just yet. It's something I'd *like* to tackle, but it'll need a fairly big rewrite of some of the scaling and drawing code to calculate the layout and map thumbnail clicks back to desktop locations...

**Comment by mdrejhon** [comment]
You could compromise:

(A) Just overlay the border on top of things (no screenshot distortion),
(B) Use a slight alpha (25% transparent, 75% opaque)

That way, the border has no effect on click positions or screenshot scaling.

**Comment by mikeclayton** [comment]
@mdrejhon - I've been working on this here - https://github.com/mikeclayton/FancyMouse/pull/24 

It basically works and lets you specify a bunch of settings (margins, borders, padding, colours) in the config file but I need to write a bunch of tests to verify the layout logic before I'm ready to release it.

I'll also send a PR to the PowerToys repo at some point once it's released here, but it depends on whether they like it when they see it as to whether it'll get merged or not...

**Comment by mdrejhon** [comment]
Thank you!  It looks like you went with your original approach to abberate exact relative positions to add a border.  

Nice -- that's algorithmically much harder than my simpler approach to simply overlay a semi-transparent border inside the screenshot rectangle -- to avoid the need for any distortions.

**Comment by mikeclayton** [comment]
Each sreenshot will have its own bezel (depending on whether there's one configured) - it'll end up looking like the last image above, i.e.:

![image](https://github.com/mikeclayton/FancyMouse/assets/1193763/ec15ea2b-3cc3-4b88-b2c9-f0679ccba101)

You'll be able to adjust the color / thickness of the border and the spacing between each screenshot in the config file.

And the screenshot thumbnails will be *stretched* (not *scaled*) to fit inside the border, which might distort the aspect ratio but it doesn't really make much difference when you actually see it unless you're using extremely large borders on extremely small screenshots (in which case, blame maths, not me :-) )...

**Comment by mikeclayton** [comment]
Released in **FancyMouse v0.0.15-preview** - https://github.com/mikeclayton/FancyMouse/releases/tag/v0.0.15-preview

**Comment by mdrejhon** [comment]
Thank you!  If you don't hear from me, that means I'm happy.

**Comment by mdrejhon** [comment]
Question.... Has Microsoft accepted this change upstream?  

I am curious, simply because the Microsoft version is less useful for those "I just wanna teleport my mouse pointer to a specific screen, without worrying about configuring multimonitor positioning" use cases.   

A spare display of mine is being used as an infoboard calendar, and I don't want my mouse pointer there unless I really want it to.  (You can make that happen by docking corners of displays, so that it is hard to move mouse pointer over there)

**Comment by mikeclayton** [comment]
Development has stalled a little bit, tbh.

It's still on my todo list, but I've not really got an ETA for it I'm afraid.

I'll create a new issue for pushing it upstream and then it might give me a nudge to get round to it :-)
